package com.provider.demo.dao;

import com.provider.demo.entity.Minister;

public interface MinisterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mins
     *
     * @mbggenerated Mon Jan 21 16:58:37 CST 2019
     */
    int deleteByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mins
     *
     * @mbggenerated Mon Jan 21 16:58:37 CST 2019
     */
    int insert(Minister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mins
     *
     * @mbggenerated Mon Jan 21 16:58:37 CST 2019
     */
    int insertSelective(Minister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mins
     *
     * @mbggenerated Mon Jan 21 16:58:37 CST 2019
     */
    Minister selectByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mins
     *
     * @mbggenerated Mon Jan 21 16:58:37 CST 2019
     */
    int updateByPrimaryKeySelective(Minister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mins
     *
     * @mbggenerated Mon Jan 21 16:58:37 CST 2019
     */
    int updateByPrimaryKey(Minister record);
}